@startuml CON02

actor Usuário
participant Sistema

Usuário -> Sistema: Solicita a listagem das contas

Sistema -> Sistema: Verifica se o usuário está autenticado

group Usuário não está autenticado
  Sistema -> Usuário: Exibe um erro informando que o usuário precisa estar autenticado
end

group Usuário está autenticado
  Sistema -> Sistema: Realiza a busca das contas do usuário logado
  Sistema -> Usuário: Exibe as contas dos usuário logado
end

@enduml